### ISSUE TITLE
When we change a fastq file we flush the reads and send them to the server, limiting batch size to 4000

### ISSUE THREAD

**Issue by Adoni5** [LooseLab/minotourcli#13]
If we don't have any other file to process, and we reach EOF we should post, otherwise roll over!

**Comment by mattloose** [comment]
Reads seem to get wiped on roll over to a new fastq file - need to understand this in more detail.

**Comment by Adoni5** [comment]
This is fixed, we flush reads on new fastq file and when we keyboard interrupt the client.
